language: java
env: MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=192m" GRADLE_OPTS="-Xmx1024m -XX:MaxPermSize=192m" TERM="dumb"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
#sudo: false
# can uncomment above after resolution of https://github.com/travis-ci/travis-ci/issues/3120
sudo: required
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y xmlstarlet jq
  - sudo chsh --shell $(which bash)
script:
  - './gradlew clean build && groovy testbuild.groovy -gradle && make TAG=SNAPSHOT BUILD_NUM=$TRAVIS_BUILD_NUMBER rpm deb && bash run-api-tests.sh && bash run-docker-tests.sh && bash run-docker-ssl-tests.sh'
addons:
  hostname: rdbuild
  apt:
    packages:
    - groovy
    - rpm
    - make
    - zip
    - unzip
    #- xmlstarlet #once added to whitelist
    #- jq #once added to whitelist
# whitelist
branches:
  only:
    - master
    - '2.6.x'

notifications:
  irc:
    - "irc.freenode.org#rundeck"
  #email: false


